Repository kieraneglin/pinchflat, pull requests merged in 2024-03, with the labels that each got.

#46 Support audio only downloads
  lib/pinchflat/profiles/media_profile.ex
  lib/pinchflat/profiles/options/yt_dlp/download_option_builder.ex
  lib/pinchflat_web/components/core_components.ex
  lib/pinchflat_web/controllers/media_profiles/media_profile_html.ex
  lib/pinchflat_web/controllers/media_profiles/media_profile_html/media_profile_form.html.heex
  test/pinchflat/profiles/options/yt_dlp/download_option_builder_test.exs
Labels: enhancement, media downloads, UI

#47 Clarify wording of source form for index frequency
  lib/pinchflat_web/controllers/sources/source_html.ex
  lib/pinchflat_web/controllers/sources/source_html/source_form.html.heex
Labels: documentation, UI

#48 Track media filesize in DB
  config/config.exs
  lib/pinchflat/media/media_item.ex
  lib/pinchflat/tasks/media_item_tasks.ex
  lib/pinchflat/tasks/source_tasks.ex
  lib/pinchflat/workers/filesystem_data_worker.ex
  lib/pinchflat/workers/video_download_worker.ex
  priv/repo/migrations/20240303021902_add_media_size_to_media_item.exs
  test/pinchflat/tasks/media_items_tasks_test.exs
  test/pinchflat/workers/filesystem_data_worker_test.exs
  test/pinchflat/workers/video_download_worker_test.exs
Labels: enhancement, media categorization

#50 Rename video-related modules to be media-related
  .iex.exs
  config/dev.exs
  config/test.exs
  lib/pinchflat/media_client/backends/yt_dlp/media.ex
  lib/pinchflat/media_client/backends/yt_dlp/media_collection.ex
  lib/pinchflat/media_client/backends/yt_dlp/metadata_file_helpers.ex
  lib/pinchflat/media_client/media_downloader.ex
  lib/pinchflat/media_client/source_details.ex
  lib/pinchflat/profiles/media_profile.ex
  lib/pinchflat/tasks/source_tasks.ex
  lib/pinchflat/workers/media_download_worker.ex
  test/pinchflat/media_client/backends/yt_dlp/command_runner_test.exs
  test/pinchflat/media_client/backends/yt_dlp/media_collection_test.exs
  test/pinchflat/media_client/backends/yt_dlp/media_test.exs
  test/pinchflat/media_client/backends/yt_dlp/metadata_parser_test.exs
  test/pinchflat/media_client/media_downloader_test.exs
  test/pinchflat/profiles/options/yt_dlp/download_option_builder_test.exs
  test/pinchflat/sources_test.exs
  test/pinchflat/tasks/source_tasks_test.exs
  test/pinchflat/workers/media_download_worker_test.exs
  test/pinchflat/workers/media_indexing_worker_test.exs
Labels: documentation, refactor

#51 More README
  README.md
  test/pinchflat/utils/filesystem_utils/file_follower_server_test.exs
Labels: bug, documentation

#52 [Bugfix] Fix basic auth in deployed apps
  README.md
  config/config.exs
  config/runtime.exs
  lib/pinchflat_web/router.ex
  test/pinchflat_web/routing_test.exs
Labels: bug, refactor

#53 Add image tag input to Github actions
  .github/workflows/build_and_push_docker.yml
Labels: enhancement

#54 Add settings model
  .iex.exs
  lib/pinchflat/application.ex
  lib/pinchflat/profiles/media_profile.ex
  lib/pinchflat/settings.ex
  lib/pinchflat/settings/setting.ex
  lib/pinchflat/startup_tasks.ex
  lib/pinchflat_web.ex
  lib/pinchflat_web/controllers/media_profiles/media_profile_controller.ex
  lib/pinchflat_web/controllers/media_profiles/media_profile_html/new.html.heex
  lib/pinchflat_web/controllers/pages/page_controller.ex
  lib/pinchflat_web/controllers/sources/source_controller.ex
  lib/pinchflat_web/controllers/sources/source_html/new.html.heex
  priv/repo/migrations/20240306173305_create_settings.exs
  test/pinchflat/settings_test.exs
  test/pinchflat/startup_tasks_test.exs
  test/pinchflat_web/controllers/media_profile_controller_test.exs
  test/pinchflat_web/controllers/page_controller_test.exs
  test/pinchflat_web/controllers/source_controller_test.exs
Labels: enhancement, refactor

#55 Adds log level to runtime config
  config/runtime.exs
Labels: enhancement

#56 [Bugfix] Runtime log level fix
  config/runtime.exs
Labels: bug

#57 [Bugfix] Resolves bug with null values in search
  lib/pinchflat/media.ex
  test/pinchflat/media_test.exs
Labels: bug

#59 Improve short detection
  lib/pinchflat/media.ex
  lib/pinchflat/media/media_item.ex
  lib/pinchflat/tasks/source_tasks.ex
  lib/pinchflat/yt_dlp/backend/media.ex
  lib/pinchflat/yt_dlp/backend/media_collection.ex
  priv/repo/migrations/20240309052602_add_short_form_to_media_items.exs
  test/pinchflat/media_test.exs
  test/pinchflat/tasks/media_items_tasks_test.exs
  test/pinchflat/tasks/source_tasks_test.exs
  test/pinchflat/yt_dlp/backend/media_collection_test.exs
  test/pinchflat/yt_dlp/backend/media_test.exs
  test/support/fixtures/media_fixtures.ex
  test/support/fixtures/sources_fixtures.ex
Labels: enhancement, media downloads, media categorization, refactor, media indexing

#63 Fast index UI
  config/config.exs
  lib/pinchflat/api/youtube_rss.ex
  lib/pinchflat/sources.ex
  lib/pinchflat/sources/source.ex
  lib/pinchflat/tasks/source_tasks.ex
  lib/pinchflat/workers/fast_indexing_worker.ex
  lib/pinchflat/workers/media_collection_indexing_worker.ex
  lib/pinchflat_web/controllers/sources/source_controller.ex
  lib/pinchflat_web/controllers/sources/source_html/fast_indexing_help.html.heex
  lib/pinchflat_web/controllers/sources/source_html/show.html.heex
  lib/pinchflat_web/controllers/sources/source_html/source_form.html.heex
  priv/repo/migrations/20240309182418_add_fast_index_to_sources.exs
  test/pinchflat/sources_test.exs
  test/pinchflat/tasks/source_tasks_test.exs
  test/pinchflat/workers/fast_indexing_worker_test.exs
  test/pinchflat/workers/media_collection_indexing_worker_test.exs
Labels: enhancement, media indexing, UI

#65 Add support modals
  lib/pinchflat/startup_tasks.ex
  lib/pinchflat_web.ex
  lib/pinchflat_web/components/core_components.ex
  lib/pinchflat_web/components/custom_components/button_components.ex
  lib/pinchflat_web/components/layouts.ex
  lib/pinchflat_web/components/layouts/partials/donate_modal.heex
  lib/pinchflat_web/components/layouts/partials/sidebar.html.heex
  lib/pinchflat_web/components/layouts/partials/upgrade_button_live.ex
  lib/pinchflat_web/components/layouts/partials/upgrade_modal.heex
  lib/pinchflat_web/components/layouts/root.html.heex
  lib/pinchflat_web/controllers/media_items/media_item_html/show.html.heex
  lib/pinchflat_web/controllers/media_profiles/media_profile_html/edit.html.heex
  lib/pinchflat_web/controllers/media_profiles/media_profile_html/index.html.heex
  lib/pinchflat_web/controllers/media_profiles/media_profile_html/new.html.heex
  lib/pinchflat_web/controllers/media_profiles/media_profile_html/show.html.heex
  lib/pinchflat_web/controllers/pages/page_html/onboarding_checklist.html.heex
  lib/pinchflat_web/controllers/searches/search_html/show.html.heex
  lib/pinchflat_web/controllers/sources/source_html/edit.html.heex
  lib/pinchflat_web/controllers/sources/source_html/index.html.heex
  lib/pinchflat_web/controllers/sources/source_html/new.html.heex
  lib/pinchflat_web/controllers/sources/source_html/show.html.heex
  lib/pinchflat_web/controllers/sources/source_html/source_form.html.heex
Labels: enhancement, media downloads, media indexing, UI

#66 Local data worker improvements
  lib/pinchflat/application.ex
  lib/pinchflat/startup_tasks.ex
  lib/pinchflat/workers/data_backfill_worker.ex
  lib/pinchflat/workers/fast_indexing_worker.ex
  test/pinchflat/workers/data_backfill_worker_test.exs
Labels: enhancement, media categorization

#67 [Bugfix] Update check origin in release environment
  config/config.exs
  config/dev.exs
Labels: bug

#69 Download cutoff date for sources
  .iex.exs
  lib/pinchflat/media.ex
  lib/pinchflat/media/media_item.ex
  lib/pinchflat/sources.ex
  lib/pinchflat/sources/source.ex
  lib/pinchflat/tasks/source_tasks.ex
  lib/pinchflat/yt_dlp/backend/media.ex
  lib/pinchflat_web/components/core_components.ex
  lib/pinchflat_web/controllers/sources/source_html/source_form.html.heex
  priv/repo/migrations/20240310230713_add_uploaded_at_to_media_items.exs
  priv/repo/migrations/20240311033214_add_download_cutoff_date_to_sources.exs
  test/pinchflat/media_test.exs
  test/pinchflat/sources_test.exs
  test/pinchflat/tasks/media_items_tasks_test.exs
  test/pinchflat/tasks/source_tasks_test.exs
  test/pinchflat/yt_dlp/backend/media_test.exs
  test/support/fixtures/media_fixtures.ex
  test/support/fixtures/sources_fixtures.ex
  test/support/testing_helper_methods.ex
Labels: enhancement, media downloads, media categorization, refactor, media indexing, UI

#71 Upgrade to Elixir 1.16.2
  .check.exs
  dev.Dockerfile
  ideas.md
  selfhosted.Dockerfile
Labels: enhancement, refactor, housekeeping

#74 Improve audio-only download
  lib/pinchflat/yt_dlp/download_option_builder.ex
  lib/pinchflat_web/controllers/media_profiles/media_profile_html/media_profile_form.html.heex
  test/pinchflat/yt_dlp/download_option_builder_test.exs
Labels: enhancement, media downloads

#75 Add local details to local dockerfile
  dev.Dockerfile
Labels: bug

#76 Onboarding improvements
  lib/pinchflat/profiles/media_profile.ex
  lib/pinchflat/profiles/output_path_builder.ex
  lib/pinchflat_web/components/layouts/root.html.heex
  lib/pinchflat_web/controllers/media_profiles/media_profile_html.ex
  lib/pinchflat_web/controllers/media_profiles/media_profile_html/media_profile_form.html.heex
  lib/pinchflat_web/controllers/pages/page_controller.ex
  lib/pinchflat_web/controllers/pages/page_html/onboarding_checklist.html.heex
  test/pinchflat_web/controllers/page_controller_test.exs
Labels: enhancement, media downloads, media categorization, UI

#79 [Bugfix] Fixes issue with grabbing source/media details when first video is a premier
  lib/pinchflat/yt_dlp/media_collection.ex
  test/pinchflat/yt_dlp/media_collection_test.exs
Labels: bug

#80 Add input validation to help with cutoff date usage
  lib/pinchflat_web/controllers/sources/source_html/source_form.html.heex
Labels: enhancement

#84 Add support for episode NFO files
  dump_all.sql
  lib/pinchflat/downloading/media_downloader.ex
  lib/pinchflat/filesystem/filesystem_helpers.ex
  lib/pinchflat/media/media_item.ex
  lib/pinchflat/metadata/metadata_file_helpers.ex
  lib/pinchflat/metadata/nfo_builder.ex
  lib/pinchflat/profiles/media_profile.ex
  lib/pinchflat/yt_dlp/media.ex
  lib/pinchflat_web/controllers/media_profiles/media_profile_html/media_profile_form.html.heex
  priv/repo/migrations/20240313175638_add_nfo_filepath_to_media_item.exs
  priv/repo/migrations/20240313175744_add_download_nfo_to_media_profile.exs
  test/pinchflat/downloading/media_downloader_test.exs
  test/pinchflat/filesystem/filesystem_helpers_test.exs
  test/pinchflat/metadata/metadata_file_helpers_test.exs
  test/pinchflat/metadata/metadata_parser_test.exs
  test/pinchflat/metadata/nfo_builder_test.exs
  test/support/testing_helper_methods.ex
Labels: enhancement, media downloads, media categorization

#85 Add media profile presets
  lib/pinchflat/downloading/output_path_builder.ex
  lib/pinchflat/profiles/media_profile.ex
  lib/pinchflat_web/components/core_components.ex
  lib/pinchflat_web/components/custom_components/button_components.ex
  lib/pinchflat_web/controllers/media_profiles/media_profile_html.ex
  lib/pinchflat_web/controllers/media_profiles/media_profile_html/media_profile_form.html.heex
Labels: enhancement, refactor, UI

#87 Append `-thumb` to thumbnails when downloading
  lib/pinchflat/downloading/download_option_builder.ex
  lib/pinchflat/metadata/metadata_parser.ex
  lib/pinchflat/profiles/media_profile.ex
  test/pinchflat/downloading/download_option_builder_test.exs
  test/pinchflat/metadata/metadata_parser_test.exs
  test/pinchflat/profiles_test.exs
  test/pinchflat_web/controllers/media_profile_controller_test.exs
Labels: enhancement, media downloads

#88 Squash all the commits from the other branch bc I broke things
  config/config.exs
  lib/pinchflat/boot/data_backfill_worker.ex
  lib/pinchflat/filesystem/filesystem_data_worker.ex
  lib/pinchflat/media/media.ex
  lib/pinchflat/metadata/source_metadata.ex
  lib/pinchflat/metadata/source_metadata_storage_worker.ex
  lib/pinchflat/sources/source.ex
  lib/pinchflat/sources/sources.ex
  lib/pinchflat/tasks/tasks.ex
  lib/pinchflat/yt_dlp/media_collection.ex
  priv/repo/migrations/20240314174731_create_source_metadata.exs
  test/pinchflat/metadata/source_metadata_storage_worker_test.exs
  test/pinchflat/slow_indexing/media_collection_indexing_worker_test.exs
  test/pinchflat/sources_test.exs
  test/pinchflat/yt_dlp/media_collection_test.exs
  test/support/fixtures/sources_fixtures.ex
Labels: enhancement, media categorization, refactor, media indexing

#86 Improve episode-level compatability with media center apps
  config/config.exs
  lib/pinchflat/boot/data_backfill_worker.ex
  lib/pinchflat/downloading/download_option_builder.ex
  lib/pinchflat/downloading/output_path_builder.ex
  lib/pinchflat/filesystem/filesystem_data_worker.ex
  lib/pinchflat/media/media.ex
  lib/pinchflat/metadata/metadata_parser.ex
  lib/pinchflat/metadata/source_metadata.ex
  lib/pinchflat/metadata/source_metadata_storage_worker.ex
  lib/pinchflat/profiles/media_profile.ex
  lib/pinchflat/sources/source.ex
  lib/pinchflat/sources/sources.ex
  lib/pinchflat/tasks/tasks.ex
  lib/pinchflat/yt_dlp/media_collection.ex
  lib/pinchflat_web/components/core_components.ex
  lib/pinchflat_web/components/custom_components/button_components.ex
  lib/pinchflat_web/controllers/media_profiles/media_profile_html.ex
  lib/pinchflat_web/controllers/media_profiles/media_profile_html/media_profile_form.html.heex
  priv/repo/migrations/20240314174731_create_source_metadata.exs
  test/pinchflat/downloading/download_option_builder_test.exs
  test/pinchflat/metadata/metadata_parser_test.exs
  test/pinchflat/metadata/source_metadata_storage_worker_test.exs
  test/pinchflat/profiles_test.exs
  test/pinchflat/slow_indexing/media_collection_indexing_worker_test.exs
  test/pinchflat/sources_test.exs
  test/pinchflat/yt_dlp/media_collection_test.exs
  test/pinchflat_web/controllers/media_profile_controller_test.exs
  test/support/fixtures/sources_fixtures.ex
Labels: enhancement, media downloads, media categorization, refactor, media indexing, UI

#89 Misc refactors 2024-03-14
  .credo.exs
  lib/pinchflat/boot/pre_job_startup_tasks.ex
  lib/pinchflat/downloading/download_option_builder.ex
  lib/pinchflat/downloading/downloading_helpers.ex
  lib/pinchflat/downloading/media_download_worker.ex
  lib/pinchflat/downloading/media_downloader.ex
  lib/pinchflat/fast_indexing/fast_indexing_helpers.ex
  lib/pinchflat/fast_indexing/fast_indexing_worker.ex
  lib/pinchflat/fast_indexing/media_indexing_worker.ex
  lib/pinchflat/filesystem/filesystem_data_worker.ex
  lib/pinchflat/filesystem/filesystem_helpers.ex
  lib/pinchflat/media/media.ex
  lib/pinchflat/metadata/source_metadata_storage_worker.ex
  lib/pinchflat/slow_indexing/media_collection_indexing_worker.ex
  lib/pinchflat/slow_indexing/slow_indexing_helpers.ex
  lib/pinchflat/sources/sources.ex
  lib/pinchflat/tasks/tasks.ex
  lib/pinchflat/yt_dlp/command_runner.ex
  lib/pinchflat/yt_dlp/media_collection.ex
  lib/pinchflat_web/controllers/sources/source_controller.ex
  mix.exs
  test/pinchflat/boot/data_backfill_worker_test.exs
  test/pinchflat/downloading/download_option_builder_test.exs
  test/pinchflat/downloading/downloading_helpers_test.exs
  test/pinchflat/downloading/media_download_worker_test.exs
  test/pinchflat/fast_indexing/fast_indexing_helpers_test.exs
  test/pinchflat/fast_indexing/fast_indexing_worker_test.exs
  test/pinchflat/fast_indexing/media_indexing_worker_test.exs
  test/pinchflat/filesystem/filesystem_data_worker_test.exs
  test/pinchflat/filesystem/filesystem_helpers_test.exs
  test/pinchflat/media_test.exs
  test/pinchflat/metadata/source_metadata_storage_worker_test.exs
  test/pinchflat/slow_indexing/media_collection_indexing_worker_test.exs
  test/pinchflat/slow_indexing/slow_indexing_helpers_test.exs
  test/pinchflat/sources_test.exs
  test/pinchflat/tasks_test.exs
  test/pinchflat/yt_dlp/media_collection_test.exs
Labels: bug, documentation, refactor

#90 Misc refactors 2024-03-15
  lib/pinchflat/downloading/media_download_worker.ex
  lib/pinchflat/fast_indexing/fast_indexing_worker.ex
  lib/pinchflat/fast_indexing/media_indexing_worker.ex
  lib/pinchflat/media/media.ex
  lib/pinchflat/metadata/source_metadata_storage_worker.ex
  lib/pinchflat/slow_indexing/media_collection_indexing_worker.ex
  lib/pinchflat/sources/sources.ex
  lib/pinchflat_web/controllers/media_profiles/media_profile_html.ex
  test/pinchflat/downloading/media_download_worker_test.exs
  test/pinchflat/fast_indexing/fast_indexing_worker_test.exs
  test/pinchflat/fast_indexing/media_indexing_worker_test.exs
  test/pinchflat/metadata/source_metadata_storage_worker_test.exs
  test/pinchflat/slow_indexing/media_collection_indexing_worker_test.exs
Labels: bug, enhancement

#95 Source NFO downloads
  lib/pinchflat/downloading/download_option_builder.ex
  lib/pinchflat/downloading/media_downloader.ex
  lib/pinchflat/metadata/metadata_file_helpers.ex
  lib/pinchflat/metadata/nfo_builder.ex
  lib/pinchflat/metadata/source_metadata_storage_worker.ex
  lib/pinchflat/sources/source.ex
  lib/pinchflat/sources/sources.ex
  lib/pinchflat/yt_dlp/media_collection.ex
  lib/pinchflat_web/controllers/media_profiles/media_profile_html/media_profile_form.html.heex
  lib/pinchflat_web/controllers/sources/source_html/source_form.html.heex
  priv/repo/migrations/20240318161405_add_nfo_path_to_sources.exs
  test/pinchflat/downloading/download_option_builder_test.exs
  test/pinchflat/metadata/metadata_file_helpers_test.exs
  test/pinchflat/metadata/nfo_builder_test.exs
  test/pinchflat/metadata/source_metadata_storage_worker_test.exs
  test/pinchflat/sources_test.exs
  test/pinchflat/yt_dlp/media_collection_test.exs
  test/support/fixtures/sources_fixtures.ex
Labels: enhancement, media downloads, media categorization, refactor, UI

#97 Improve index tables and improved consistency
  lib/pinchflat_web/components/custom_components/text_components.ex
  lib/pinchflat_web/controllers/media_items/media_item_html/show.html.heex
  lib/pinchflat_web/controllers/media_profiles/media_profile_html/edit.html.heex
  lib/pinchflat_web/controllers/media_profiles/media_profile_html/index.html.heex
  lib/pinchflat_web/controllers/media_profiles/media_profile_html/show.html.heex
  lib/pinchflat_web/controllers/pages/page_html/onboarding_checklist.html.heex
  lib/pinchflat_web/controllers/searches/search_html/show.html.heex
  lib/pinchflat_web/controllers/sources/source_html/edit.html.heex
  lib/pinchflat_web/controllers/sources/source_html/index.html.heex
  lib/pinchflat_web/controllers/sources/source_html/show.html.heex
  test/pinchflat_web/controllers/media_profile_controller_test.exs
  test/pinchflat_web/controllers/source_controller_test.exs
Labels: enhancement, refactor, UI

#98 Source title regex filtering
  config/runtime.exs
  lib/pinchflat/media/media.ex
  lib/pinchflat/sources/source.ex
  lib/pinchflat_web/controllers/media_profiles/media_profile_html/media_profile_form.html.heex
  lib/pinchflat_web/controllers/sources/source_html/source_form.html.heex
  priv/repo/extensions/sqlean-linux-arm/crypto.so
  priv/repo/extensions/sqlean-linux-arm/define.so
  priv/repo/extensions/sqlean-linux-arm/fileio.so
  priv/repo/extensions/sqlean-linux-arm/fuzzy.so
  priv/repo/extensions/sqlean-linux-arm/ipaddr.so
  priv/repo/extensions/sqlean-linux-arm/math.so
  priv/repo/extensions/sqlean-linux-arm/regexp.so
  priv/repo/extensions/sqlean-linux-arm/sqlean.so
  priv/repo/extensions/sqlean-linux-arm/stats.so
  priv/repo/extensions/sqlean-linux-arm/text.so
  priv/repo/extensions/sqlean-linux-arm/unicode.so
  priv/repo/extensions/sqlean-linux-arm/uuid.so
  priv/repo/extensions/sqlean-linux-arm/vsv.so
  priv/repo/extensions/sqlean-linux-x86/crypto.so
  priv/repo/extensions/sqlean-linux-x86/define.so
  priv/repo/extensions/sqlean-linux-x86/fileio.so
  priv/repo/extensions/sqlean-linux-x86/fuzzy.so
  priv/repo/extensions/sqlean-linux-x86/ipaddr.so
  priv/repo/extensions/sqlean-linux-x86/math.so
  priv/repo/extensions/sqlean-linux-x86/regexp.so
  priv/repo/extensions/sqlean-linux-x86/sqlean.so
  priv/repo/extensions/sqlean-linux-x86/stats.so
  priv/repo/extensions/sqlean-linux-x86/text.so
  priv/repo/extensions/sqlean-linux-x86/unicode.so
  priv/repo/extensions/sqlean-linux-x86/uuid.so
  priv/repo/extensions/sqlean-linux-x86/vsv.so
  priv/repo/migrations/20240320153902_add_title_regex_to_source.exs
  test/pinchflat/media_test.exs
Labels: enhancement, media downloads, media indexing, UI

#99 Misc indexing improvements
  lib/pinchflat/slow_indexing/file_follower_server.ex
  lib/pinchflat/slow_indexing/slow_indexing_helpers.ex
  lib/pinchflat/sources/source.ex
  priv/repo/migrations/20240320181210_remove_unique_index_from_sources.exs
  test/pinchflat/sources_test.exs
Labels: enhancement, refactor, media indexing

#100 Update logo
  README.md
  lib/pinchflat_web/components/layouts/onboarding.html.heex
  lib/pinchflat_web/components/layouts/partials/header.html.heex
  lib/pinchflat_web/components/layouts/partials/sidebar.html.heex
  lib/pinchflat_web/components/layouts/root.html.heex
  priv/static/favicon.ico
  priv/static/images/icon.png
  priv/static/images/logo.png
  priv/static/images/originals/icon-with-background.png
  priv/static/images/originals/logo-teal-wordmark.png
  priv/static/images/originals/logo-white-wordmark-with-background.png
  priv/static/images/originals/logo-white-wordmark.png
  priv/static/images/originals/logo.png
Labels: UI

#101 Improve README
  .github/pull_request_template.md
  README.md
  priv/static/images/app-form-screenshot.png
  priv/static/images/app-screenshot.png
Labels: housekeeping

#108 Add media streaming
  .iex.exs
  .sobelow-conf
  README.md
  lib/pinchflat/boot/pre_job_startup_tasks.ex
  lib/pinchflat/media/media_item.ex
  lib/pinchflat/sources/source.ex
  lib/pinchflat_web/controllers/media_items/media_item_controller.ex
  lib/pinchflat_web/controllers/media_items/media_item_html.ex
  lib/pinchflat_web/controllers/media_items/media_item_html/media_preview.heex
  lib/pinchflat_web/controllers/media_items/media_item_html/show.html.heex
  lib/pinchflat_web/router.ex
  priv/repo/migrations/20240323165649_add_uuid_to_source_and_media.exs
  test/pinchflat/media_test.exs
  test/pinchflat/sources_test.exs
  test/pinchflat_web/controllers/media_item_controller_test.exs
  test/support/fixtures/media_fixtures.ex
Labels: enhancement, media categorization, UI

#112 Adds a method for retrying stuck jobs
  .iex.exs
  lib/pinchflat/boot/pre_job_startup_tasks.ex
Labels: bug

#114 Improve preflight file permissions check
  README.md
  lib/pinchflat/boot/pre_job_startup_tasks.ex
  lib/pinchflat/filesystem/filesystem_helpers.ex
  lib/pinchflat/release.ex
  rel/overlays/bin/check_file_permissions
  rel/overlays/bin/docker_start
  test/pinchflat/filesystem/filesystem_helpers_test.exs
Labels: documentation, housekeeping

#115 Add GHCR support
  README.md
Labels: housekeeping

#116 Cookie auth
  .iex.exs
  README.md
  config/config.exs
  config/dev.exs
  config/runtime.exs
  lib/pinchflat/boot/pre_job_startup_tasks.ex
  lib/pinchflat/release.ex
  lib/pinchflat/yt_dlp/command_runner.ex
  selfhosted.Dockerfile
  test/pinchflat/downloading/download_option_builder_test.exs
  test/pinchflat/yt_dlp/command_runner_test.exs
  test/test_helper.exs
Labels: enhancement, media downloads, media categorization, media indexing

#119 Improve default recommendation for artist placeholder
  lib/pinchflat/downloading/output_path_builder.ex
  lib/pinchflat_web/controllers/media_profiles/media_profile_html.ex
Labels: enhancement, media categorization

#120 [Internal] Store source images in internal metadata
  lib/pinchflat/metadata/metadata_file_helpers.ex
  lib/pinchflat/metadata/source_metadata.ex
  lib/pinchflat/metadata/source_metadata_storage_worker.ex
  priv/repo/migrations/20240325174728_add_image_attrs_to_source_metadata.exs
  test/pinchflat/metadata/metadata_file_helpers_test.exs
  test/pinchflat/metadata/source_metadata_storage_worker_test.exs
Labels: enhancement, housekeeping

#121 [Internal] Removed old startup tasks
  lib/pinchflat/boot/data_backfill_worker.ex
  lib/pinchflat/boot/pre_job_startup_tasks.ex
  test/pinchflat/boot/data_backfill_worker_test.exs
Labels: housekeeping

#129 [Bugfix] Expose port in Dockerfile and force IPv4
  config/runtime.exs
  lib/pinchflat_web/components/layouts/partials/sidebar.html.heex
  selfhosted.Dockerfile
Labels: bug, enhancement

#123 Generate rss feeds
  config/config.exs
  config/runtime.exs
  lib/pinchflat/boot/pre_job_startup_tasks.ex
  lib/pinchflat/podcasts/podcast_helpers.ex
  lib/pinchflat/podcasts/rss_feed_builder.ex
  lib/pinchflat/utils/datetime_utils.ex
  lib/pinchflat_web.ex
  lib/pinchflat_web/components/core_components.ex
  lib/pinchflat_web/components/custom_components/button_components.ex
  lib/pinchflat_web/components/custom_components/tab_components.ex
  lib/pinchflat_web/controllers/media_items/media_item_controller.ex
  lib/pinchflat_web/controllers/media_items/media_item_html/show.html.heex
  lib/pinchflat_web/controllers/media_profiles/media_profile_html/media_profile_form.html.heex
  lib/pinchflat_web/controllers/media_profiles/media_profile_html/show.html.heex
  lib/pinchflat_web/controllers/podcasts/podcast_controller.ex
  lib/pinchflat_web/controllers/sources/source_html.ex
  lib/pinchflat_web/controllers/sources/source_html/show.html.heex
  lib/pinchflat_web/endpoint.ex
  lib/pinchflat_web/router.ex
  priv/repo/migrations/20240325222242_add_uuid_to_source_and_media.exs
  priv/repo/migrations/20240325222243_backfill_content_uuids.exs
  test/pinchflat/metadata/source_metadata_storage_worker_test.exs
  test/pinchflat/podcasts/podcast_helpers_test.exs
  test/pinchflat/podcasts/rss_feed_builder_test.exs
  test/pinchflat/utils/datetime_utils_test.exs
  test/pinchflat_web/controllers/podcast_controller_test.exs
  test/pinchflat_web/routing_test.exs
  test/support/fixtures/media_fixtures.ex
  test/support/fixtures/sources_fixtures.ex
Labels: enhancement, media categorization, refactor, UI

#110 RSS feed for sources
  .sobelow-conf
  README.md
  config/config.exs
  config/runtime.exs
  lib/pinchflat/media/media_item.ex
  lib/pinchflat/podcasts/podcast_helpers.ex
  lib/pinchflat/podcasts/rss_feed_builder.ex
  lib/pinchflat/sources/source.ex
  lib/pinchflat/utils/datetime_utils.ex
  lib/pinchflat_web.ex
  lib/pinchflat_web/components/core_components.ex
  lib/pinchflat_web/components/custom_components/button_components.ex
  lib/pinchflat_web/components/custom_components/tab_components.ex
  lib/pinchflat_web/controllers/media_items/media_item_controller.ex
  lib/pinchflat_web/controllers/media_items/media_item_html.ex
  lib/pinchflat_web/controllers/media_items/media_item_html/media_preview.heex
  lib/pinchflat_web/controllers/media_items/media_item_html/show.html.heex
  lib/pinchflat_web/controllers/media_profiles/media_profile_html/media_profile_form.html.heex
  lib/pinchflat_web/controllers/media_profiles/media_profile_html/show.html.heex
  lib/pinchflat_web/controllers/podcasts/podcast_controller.ex
  lib/pinchflat_web/controllers/sources/source_html.ex
  lib/pinchflat_web/controllers/sources/source_html/show.html.heex
  lib/pinchflat_web/endpoint.ex
  lib/pinchflat_web/router.ex
  priv/repo/migrations/20240325222242_add_uuid_to_source_and_media.exs
  priv/repo/migrations/20240325222243_backfill_content_uuids.exs
  priv/repo/migrations/20240327165841_add_index_to_uuid_fields.exs
  test/pinchflat/media_test.exs
  test/pinchflat/metadata/source_metadata_storage_worker_test.exs
  test/pinchflat/podcasts/podcast_helpers_test.exs
  test/pinchflat/podcasts/rss_feed_builder_test.exs
  test/pinchflat/sources_test.exs
  test/pinchflat/utils/datetime_utils_test.exs
  test/pinchflat_web/controllers/media_item_controller_test.exs
  test/pinchflat_web/controllers/podcast_controller_test.exs
  test/pinchflat_web/routing_test.exs
  test/support/fixtures/media_fixtures.ex
  test/support/fixtures/sources_fixtures.ex
Labels: documentation, enhancement, media categorization, refactor, UI

#134 [Enhancement] Show total count of downloaded media on Source page
  lib/pinchflat_web/controllers/sources/source_controller.ex
  lib/pinchflat_web/controllers/sources/source_html/show.html.heex
Labels: enhancement, UI

#135 [Enhancement] Disable Index Frequency field when fast indexing is enabled
  lib/pinchflat_web/components/core_components.ex
  lib/pinchflat_web/controllers/sources/source_html/source_form.html.heex
Labels: enhancement, UI

#136 [Bugfix] updated fast indexing to respect title filter regex
  lib/pinchflat/media/media.ex
  test/pinchflat/media_test.exs
Labels: bug

#142 [Refactor] Refactored Media context into context + queries
  lib/pinchflat/fast_indexing/fast_indexing_helpers.ex
  lib/pinchflat/media/media.ex
  lib/pinchflat/media/media_query.ex
  lib/pinchflat/sources/sources.ex
  lib/pinchflat_web/controllers/sources/source_controller.ex
  test/pinchflat/media_test.exs
Labels: refactor, housekeeping

#144 [Feature] Add SponsorBlock-based section removal
  lib/pinchflat/downloading/download_option_builder.ex
  lib/pinchflat/profiles/media_profile.ex
  lib/pinchflat_web/components/core_components.ex
  lib/pinchflat_web/controllers/media_profiles/media_profile_html.ex
  lib/pinchflat_web/controllers/media_profiles/media_profile_html/media_profile_form.html.heex
  priv/repo/migrations/20240328160057_add_sponsorblock_to_media_profiles.exs
  test/pinchflat/downloading/download_option_builder_test.exs
Labels: enhancement, media downloads, UI

#145 [Triage] Allow changing SQLite journal mode
  README.md
  config/config.exs
  config/runtime.exs
  config/test.exs
  lib/pinchflat/release.ex
Labels: bug, triage

#146 [Enhancement] Start tracking a media item's duration
  lib/pinchflat/media/media_item.ex
  lib/pinchflat/metadata/metadata_parser.ex
  lib/pinchflat/podcasts/rss_feed_builder.ex
  lib/pinchflat/yt_dlp/media.ex
  priv/repo/migrations/20240328221845_add_duration_to_media_items.exs
  test/pinchflat/downloading/media_downloader_test.exs
  test/pinchflat/metadata/metadata_parser_test.exs
  test/pinchflat/yt_dlp/media_test.exs
Labels: enhancement, media categorization

#141 [Housekeeping] Add release workflow
  .github/workflows/release.yml
Labels: housekeeping

#147 [Housekeeping] Add release workflow (takeover)
  .github/workflows/docker_release.yml
Labels: housekeeping

#150 [Enhancement] Misc fixes 2024-03-29
  config/test.exs
  lib/pinchflat/downloading/media_download_worker.ex
  lib/pinchflat/podcasts/rss_feed_builder.ex
  lib/pinchflat_web/controllers/pages/page_html/home.html.heex
  lib/pinchflat_web/router.ex
  mix.exs
  mix.lock
  test/pinchflat/downloading/media_download_worker_test.exs
Labels: bug, enhancement, housekeeping
