Repository kieraneglin/pinchflat, pull requests merged in 2024-10, with the labels that each got.

#402 [Bugfix] Resolve invalid timezone error
  mix.lock
Labels: bugfix

#413 [Docs] document that BASE_ROUTE_PATH requires the prefix to be stripped
  README.md
Labels: documentation

#432 [Bugfix] Fix off-by-1 error for retention date logic
  lib/pinchflat/downloading/media_retention_worker.ex
  lib/pinchflat/media/media_query.ex
  test/pinchflat/downloading/media_retention_worker_test.exs
  test/pinchflat/media_test.exs
Labels: bugfix

#434 [Enhancement] Misc. UI updates
  lib/pinchflat_web/components/custom_components/text_components.ex
  lib/pinchflat_web/controllers/media_items/media_item_html/actions_dropdown.html.heex
  lib/pinchflat_web/controllers/media_items/media_item_html/media_preview.heex
  lib/pinchflat_web/controllers/media_items/media_item_html/show.html.heex
  lib/pinchflat_web/controllers/media_profiles/media_profile_html/actions_dropdown.html.heex
  lib/pinchflat_web/controllers/sources/source_html/actions_dropdown.html.heex
  lib/pinchflat_web/controllers/sources/source_html/show.html.heex
Labels: enhancement

#436 [Enhancement] Improve error message when adding a source who's details can't be queried by URL
  lib/pinchflat/sources/sources.ex
  lib/pinchflat/yt_dlp/media_collection.ex
  test/pinchflat/sources_test.exs
  test/pinchflat/yt_dlp/media_collection_test.exs
Labels: enhancement

#437 [Housekeeping] Reinstated container root password rules
  README.md
  docker/selfhosted.Dockerfile
Labels: housekeeping

#442 [Bugfix] Ensure that `playlist_index` remains persisted in all cases
  lib/pinchflat/media/media.ex
  test/pinchflat/media_test.exs
Labels: bugfix

#447 [Enhancement] Improve short detection logic (again)
  lib/pinchflat/yt_dlp/media.ex
  test/pinchflat/fast_indexing/fast_indexing_helpers_test.exs
  test/pinchflat/slow_indexing/slow_indexing_helpers_test.exs
  test/pinchflat/yt_dlp/media_test.exs
  test/support/fixtures/media_fixtures.ex
  test/support/fixtures/sources_fixtures.ex
Labels: enhancement
