Repository kieraneglin/pinchflat, pull requests merged in 2025-04, with the labels that each got.

#696 [Dev] Improve internal file follower server messaging
  lib/pinchflat/slow_indexing/file_follower_server.ex
Labels: dev

#686 [Docs] Add podman to README
  README.md
Labels: documentation

#697 [Bugfix] Fix header link when using `BASE_ROUTE_PATH`
  lib/pinchflat_web/components/layouts/partials/sidebar.html.heex
Labels: bugfix

#708 [Enhancement] Sorting sources is now case-insensitive
  lib/pinchflat_web/controllers/sources/source_live/index_table_live.ex
  test/pinchflat_web/controllers/sources/index_table_live_test.exs
Labels: enhancement
